name = "ccc-test-cf"
main = "_worker.js"
compatibility_date = "2025-05-14"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "104.17.130.226:50008"
UUID = "e23913d7-6038-4c7a-b6e3-25685fcacdf5"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
